# .pre-commit-config.yaml
repos:
-   repo: https://github.com/psf/black
    rev: 24.3.0  # Use a specific version of Black for consistency
    hooks:
    -   id: black
        language_version: python3 # Specify the Python version Black should use
